objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
	<nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CICD_PromotionTriggerActions.cls
public with sharing class CICD_PromotionTriggerActions {
    public static void updateUserStoriesWithPromotionStatus(Map<id,copado__Promotion__c> newMap , Map<id,copado__Promotion__c> oldMap){

        try{
            List<id> statusChangedIds = new List<id>();
            List<copado__User_Story__c> userStoriesToUpdate = new List<copado__User_Story__c>();

            for(copado__Promotion__c promotion : newMap.values()){
                if(promotion.copado__Status__c != oldMap.get(promotion.id).copado__Status__c) statusChangedIds.add(promotion.id);
            }

            for(copado__Promoted_User_Story__c promotedStory : [select id,copado__User_Story__c,copado__Promotion__c from copado__Promoted_User_Story__c where copado__Promotion__c in :statusChangedIds]){
                userStoriesToUpdate.add(new copado__User_Story__c(
                    id = promotedStory.copado__User_Story__c,
                    CICD_LastDeploymentStatus__c = newMap.get(promotedStory.copado__Promotion__c).copado__Status__c
                ));
            }

            
            if(userStoriesToUpdate.size() > 0 ) Update userStoriesToUpdate;


        }catch(Exception ex){

            if(newMap != null && newMap.values() != null)  CICD_TriggerFactory.propagateError( newMap.values() , ex.getMessage() );

        }
  
    }
}