objects/copado__Environment__c.object
<CustomObject>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Back_Promotion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the promotion is from a higher environment to a lower environment in the deployment flow.</description>
        <label>Back Promotion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The selected Project should be linked to an active Deployment Flow</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will provide the ability to deploy User Stories within a Release.</description>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The credential to the Source Environment that should be used when creating a deployment. This may be auto-populated, if left blank, based on the project&apos;s deployment flow if you are the owner of an Org Credential to the Source Environment.</inlineHelpText>
        <label>Source Org Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.copado__Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.copado__Source_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Promotions (Source Org Credential)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
	<nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CICD_PromotionTriggerTest.cls
@isTest(seeAllData = true)
public  class CICD_PromotionTriggerTest {
    
    public static testMethod void testStatusUpdate(){
        try{
            Test.startTest();
            
            copado__Deployment_Flow__c  deploymentFlow = [select id from copado__Deployment_Flow__c where Name=:Label.CICD_DeploymentFlowNameForTestClass limit 1];
            
            copado__Project__c projectRecord = (copado__Project__c) CICD_TestFactory.createSObject(new copado__Project__c(
                copado__Deployment_Flow__c = deploymentFlow.id
            ));
            insert projectRecord;
            
            copado__User_Story__c userStoryRecord = (copado__User_Story__c) CICD_TestFactory.createSObject(new copado__User_Story__c( 
                copado__Promote_and_Deploy__c = true,
                copado__Project__c = projectRecord.id
            ));            
            insert userStoryRecord;
            
            
            
            copado__Org__c orgCredential =  [select id,copado__Environment__c from copado__Org__c where copado__userName__c LIKE :Label.CICD_CredentialsForTestClass limit 1];
            
            
            copado__Promotion__c promotionRecord = (copado__Promotion__c) CICD_TestFactory.createSObject(new copado__Promotion__c(                    
                copado__Project__c = projectRecord.id,            
                copado__Back_Promotion__c = false,
                copado__Source_Environment__c = orgCredential.copado__Environment__c,
                copado__Source_Org_Credential__c = orgCredential.id,                    
                copado__Status__c = 'CICD_PromotionTriggerTest'
                
            ));
            insert promotionRecord;
            
            copado__Promoted_User_Story__c promotedUsRecord = (copado__Promoted_User_Story__c) CICD_TestFactory.createSObject(new copado__Promoted_User_Story__c(
                copado__Promotion__c = promotionRecord.id,
                copado__User_Story__c = userStoryRecord.id
            ));
            insert promotedUsRecord;
            
            CICD_TriggerFactory.triggerExecutionCheck = new Map<string,boolean>();
            
            promotionRecord.copado__Status__c = 'In Progress';
            update promotionRecord;
            
            CICD_TriggerFactory.triggerExecutionCheck = new Map<string,boolean>();
            delete promotionRecord;
            
            CICD_TriggerFactory.triggerExecutionCheck = new Map<string,boolean>();
            undelete promotionRecord;
            
            //additional coverage
            CICD_PromotionTriggerActions.updateUserStoriesWithPromotionStatus(null, null);
            
            
            //-------CICD_Contoller methods-------//
            CICD_Controller.deployPromotion(promotionRecord.id, 'false', 'Release Name', 'INT', 'RunSpecifiedTests');
            CICD_Controller.getLatestDeployment(promotionRecord.id);   
            
            
            Test.stopTest();
        }catch(Exception ex){
            System.debug( '>> Test Setup failed >> ' + ex.getMessage());
        }
        
        
        
    }
    
    public static testMethod void testPromoteStories(){
        try{
            Test.startTest();
            
            copado__Release__c rel = [SELECT Id, Name from copado__Release__c LIMIT 1];
            List<copado__User_Story__c> stories = [SELECT Id, Name from copado__User_Story__c LIMIT 1];         
            
            List<String> storyIds = new List<String>();
            
            for(copado__User_Story__c story : stories){
                storyIds.add(story.Id);
            }
            
            String storyIdStr = JSON.serialize(storyIds);
            
            CICD_Controller.promoteStories(storyIdStr, rel.Id, 'INT');  
            
            Test.stopTest(); 
            
        }catch(Exception ex){
            System.debug('>> test method testPromoteStories failed ' + ex.getMessage() );
        }
        
    }
    
}